var PredefinedFunctions = {
    //Math Functions
    abs: function(num){ return Math.abs(num); },
    acos: function(num){ return Math.acos(num); },
    acosh: function(num){ return Math.acosh(num); },
    asin: function(num){ return Math.asin(num); },
    asinh: function(num){ return Math.asinh(num); },
    atan: function(num){ return Math.atan(num); },
    atanh: function(num){ return Math.atanh(num); },
    atan2: function(y, x){ return Math.atan2(y, x); },
    cbrt: function(num){ return Math.cbrt(num); },
    ceil: function(num){ return Math.ceil(num); },
    clz32: function(num){ return Math.clz32(num); },
    cos: function(num){ return Math.cos(num); },
    cosh: function(num){ return Math.cosh(num); },
    exp: function(num){ return Math.exp(num); },
    expm1: function(num){ return Math.expm1(num); },
    floor: function(num){ return Math.floor(num); },
    fround: function(num){ return Math.fround(num); },
    hypot: function(){ return Math.hypot.apply(this, arguments); },
    imul: function(a, b){ return Math.imul(a, b); },
    log: function(num){ return Math.log(num); },
    log1p: function(num){ return Math.log1p(num); },
    log10: function(num){ return Math.log10(num); },
    log2: function(num){ return Math.log2(num); },
    min: function(){ return Math.min.apply(this, arguments); },
    max: function(){ return Math.max.apply(this, arguments); },
    pow: function(x, y){ return Math.pow(x, y); },
    random: function(num){ return Math.random() * (num || 1); },
    round: function(num){ return Math.round(num); },
    sign: function(num){ return Math.sign(num); },
    sin: function(num){ return Math.sin(num); },
    sinh: function(num){ return Math.sinh(num); },
    sqrt: function(num){ return Math.sqrt(num); },
    tan: function(num){ return Math.tan(num); },
    tanh: function(num){ return Math.tanh(num); },
    trunc: function(num){ return Math.trunc(num); },
};

var PredefinedConsts = {
    E: Math.E,
    LN2: Math.LN2,
    LN10: Math.LN10,
    LOG2E: Math.LOG2E,
    LOG10E: Math.LOG10E,
    PI: Math.PI,
    SQRT1_2: Math.SQRT1_2,
    SQRT2: Math.SQRT2,
    EPSILON: Number.EPSILON,
    MAX_VALUE: Number.MAX_VALUE,
    MIN_VALUE: Number.MIN_VALUE,
    NEGATIVE_INFINITY: Number.NEGATIVE_INFINITY,
    POSITIVE_INFINITY: Number.POSITIVE_INFINITY,
    get NOW(){ return Date.now(); }
};
